version: '3.8'

services:

  seq:
   container_name: seq_log
   image: datalust/seq:latest
   environment:
    - ACCEPT_EULA=Y
   ports:
    - "8081:8081"
   networks:
    - codewithvlad
   volumes:
    - seq-data:/data

networks:
  codewithvlad:
    name: codewithvlad

volumes:
  seq-data: